// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ernpuphnbyoklpsbaaop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVybnB1cGhuYnlva2xwc2JhYW9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzODgxNjYsImV4cCI6MjA2Nzk2NDE2Nn0.dfhPV7qS59h-F-7UIRA1THkzfYUsmwZMQag1iuabH10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});